article_base/article_base/urls.py
from django.contrib import admin
from django.urls import path
from mainapp import views as mainapp
from libraryapp import views as libraryapp
from shelfapp import views as shelfapp
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include


urlpatterns = [
    path('', mainapp.index, name='main'),
    path('library/', include('libraryapp.urls', namespace='library')),
    path('bookshelf/', include('shelfapp.urls', namespace='bookshelf')),
    path('profile', libraryapp.library, name='profile'),
    path('admin/', admin.site.urls, name='admin'),
    path('auth/', include('authapp.urls', namespace='auth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

article_base/authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
]

article_base/mainapp/views.py
from django.shortcuts import render
import json

# added open from json file links in menu

with open('static/json/links.json', 'r', encoding="UTF-8") as read_file:
    links = json.load(read_file)['links']
# Create your views here.


def index(request):
    title = 'Главная'
    content = {'title': title,
               'links': links,
               }
    return render(request, "mainapp/index.html", content)


def library(request):
    pass


def bookshelf(request):
    pass


def profile(request):
    pass

article_base/mainapp/templates/mainapp/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    {% block css %}
        <!--<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}"> -->
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% endblock %}

    {% block javascript %}

    {% endblock %}
</head>
<body>
    {% if user.is_authenticated %}
    <div class="container">
        {% block header %}
        <div class="header">
            {% include 'mainapp/includes/inc_menu.html' %}
		</div>
        {% endblock %}
        <div class="clear_both"></div>
        {% block content %}

        {% endblock %}

        <div class="empty"></div>
    </div>
    <div class="clear_both"></div>
    {% block footer %}
        <div class="footer">
            <p>Центр Келдыша. Вадим Баженов. 2019 г.</p>
        </div>
    {% endblock %}
    {% else %}
        <div class="auth_content">
            <h3><a href="{% url 'auth:register' %}">Зарегистрируйтесь</a> или <a href="{% url 'auth:login' %}" >войдите</a></h3>
        </div>
    {% endif %}
</body>
</html>

article_base/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
		{% block content %}
		<div class="article">
			<img src="">
			<h1 class="article_name">Приветствую, {{ user.first_name }} !</h1>
			<hr>
			<div class="abstract">Добро пожаловать в базу данных статей, посвящённых тематике
				Элеткроракетных Двигателей!<br>Надеюсь, что этот инструмент сделает поиск актуальных материалов
				легче и приятнее.</div>
			<hr>
		</div>
		{% endblock %}