article_base/article_base/urls.py
from django.contrib import admin
from django.urls import path
from mainapp import views as mainapp
from libraryapp import views as libraryapp
from shelfapp import views as shelfapp
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include


urlpatterns = [
    path('', mainapp.index, name='main'),
    path('library/', include('libraryapp.urls', namespace='library')),
    path('bookshelf/', include('shelfapp.urls', namespace='bookshelf')),
    path('profile', libraryapp.library, name='profile'),
    path('admin/', admin.site.urls, name='admin'),
    path('auth/', include('authapp.urls', namespace='auth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

article_base/authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
]

article_base/libraryapp/urls.py
from django.urls import path

import libraryapp.views as libraryapp

app_name = 'libraryapp'

urlpatterns = [
    path('', libraryapp.library, name='index'),
    path('page/<int:page>/', libraryapp.library, name='page'),
    path('listview/', libraryapp.ArticleView.as_view(), name='listview'),
    path('create_author/', libraryapp.CreateAuthor.as_view(), name='create_author'),
    path('create_theme/<int:author_id>/', libraryapp.CreateTheme.as_view(), name='create_theme'),
    path('create_ref/<int:author_id>/<int:theme_id>/', libraryapp.CreateRef.as_view(), name='create_ref'),
    path('create_article/<int:author_id>/<int:theme_id>/<int:ref_id>', libraryapp.CreateArticle.as_view(), name='create_article'),
    path('edit_article/<int:pk>/', libraryapp.EditArticle.as_view(), name='edit_article'),
    path('edit_theme/<int:article_id>/<int:pk>/', libraryapp.EditTheme.as_view(), name='edit_theme'),
    path('edit_author/<int:article_id>/<int:pk>/', libraryapp.EditAuthor.as_view(), name='edit_author'),
    path('edit_refs/<int:article_id>/<int:pk>/', libraryapp.EditRefs.as_view(), name='edit_refs'),
    path('article/<int:pk>/', libraryapp.article, name='article'),
    path('add_shelf/<int:pk>/', libraryapp.add_shelf, name='add_shelf'),
    path('delete_from_shelf/<int:pk>', libraryapp.delete_from_shelf, name='delete_from_shelf'),
    path('open_pdf/<int:pk>/', libraryapp.open_pdf, name='open_pdf'),
]

article_base/libraryapp/forms.py
from django import forms
from .models import Article, Authors, Themes, Sources, References


class AuthorCreationForm(forms.ModelForm):
    class Meta:
        model = Authors
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(AuthorCreationForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ThemeCreationForm(forms.ModelForm):
    class Meta:
        model = Themes
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ThemeCreationForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class SourceCreationForm(forms.ModelForm):
    class Meta:
        model = Sources
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(SourceCreationForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ReferenceCreationForm(forms.ModelForm):
    class Meta:
        model = References
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ReferenceCreationForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ArticleCreationForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ArticleCreationForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            print(field.initial, field_name)
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

article_base/libraryapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.conf import settings
from .models import Sources, Themes, Article, Authors, References
from .forms import ArticleCreationForm, AuthorCreationForm, ThemeCreationForm, SourceCreationForm, ReferenceCreationForm
from shelfapp.models import Bookshelf
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
import json
from django.urls import reverse
from django.core.paginator import Paginator
import os
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView
from django.urls import reverse_lazy
# Create your views here.


def load_links():
    with open('static/json/links.json', 'r', encoding="UTF-8") as read_file:
        links = json.load(read_file)['links']
        return links


def load_themes():
    with open('static/json/themes.json', 'r', encoding='cp1251') as themes_json:
        themes = json.load(themes_json)['themes']
        return themes


def load_sources():
    with open('static/json/sources.json', 'r', encoding='cp1251') as sources_json:
        sources = json.load(sources_json)['sources']
        return sources


themes = load_themes()
sources = Sources.objects.all()
links = load_links()


def filter_articles(articles, request):

    if request.method == 'POST':
        request_themes = {}
        request_sources = []
        request_dict = {}
        request_possible = ["title",
                            "doi",
                            "year__gte",
                            "year__lte",
                            "ours"
                            ]
        request_authors = []
        request_themes_id = []
        request_sources_id = []

        for key in request.POST:
            if key in themes:
                request_themes[key] = True
            elif key in request_possible and request.POST[key] != '':
                request_dict[key] = request.POST[key]
            for source in sources:
                if key in source.source:
                    request_sources.append(key)

        for theme in Themes.objects.filter(**request_themes):
            request_themes_id.append(theme.id)

        for author in Authors.objects.all():
            if request.POST['author'] in author.get_list:
                request_authors.append(author.id)

        for source in request_sources:
            request_sources_id.append(Sources.objects.filter(source=source)[0].id)

        if len(request_authors) != 0:
            request_dict['author__id__in'] = request_authors
        if len(request_themes_id) != 0:
            request_dict['theme__id__in'] = request_themes_id
        if len(request_sources_id) != 0:
            request_dict['source__id__in'] = request_sources_id

        if len(request_authors) == 0 and len(request_themes_id) == 0 and \
           len(request_sources_id) == 0 and request.POST['title'] == ''and \
           request.POST['doi'] == '' and request.POST['year'] == '':
            return []
        else:
            return Article.objects.filter(**request_dict)
    else:
        return Article.objects.all()


def library(request, page=1):
    title = 'Библиотека'
    articles = Article.objects.all()

    articles = filter_articles(articles, request)

    paginator = Paginator(articles, 4)
    try:
        page_articles = paginator.page(page)
    except PageNotAnInteger:
        page_articles = paginator.page(1)
    except EmptyPage:
        page_articles = paginator.page(paginator.num_pages)

    content = {'title': title,
               'themes': themes,
               'sources': sources,
               'links': links,
               'articles': page_articles,
               }
    return render(request, "libraryapp/library.html", content)


class ArticleView(ListView):
    model = Article
    template_name = 'libraryapp/list_view.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ArticleView, self).get_context_data(**kwargs)
        context['stuff'] = 'some_stuff'
        return context


class CreateArticle(CreateView):
    model = Article
    template_name = 'libraryapp/create_article.html'
    success_url = reverse_lazy('libraryapp:index')
    form_class = ArticleCreationForm

    def __init__(self):
        self.author_id = 0
        self.theme_id = 0
        self.ref_id = 0

    def get(self, request, *args, **kwargs):
        self.author_id = self.kwargs['author_id']
        self.theme_id = self.kwargs['theme_id']
        self.ref_id = self.kwargs['ref_id']
        self.initial['author'] = Authors.objects.get(pk=self.author_id)
        self.initial['theme'] = Themes.objects.get(pk=self.theme_id)
        self.initial['reference'] = References.objects.get(pk=self.ref_id)
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(CreateArticle, self).get_context_data(**kwargs)
        context["action_url"] = 'libraryapp:create_article'
        context["author_id"] = self.author_id
        context["theme_id"] = self.theme_id
        context["ref_id"] = self.ref_id
        return context


class CreateAuthor(CreateView):
    model = Authors
    template_name = 'libraryapp/create_author.html'
    success_url = reverse_lazy('libraryapp:index')
    form_class = AuthorCreationForm

    def get_context_data(self, **kwargs):
        context = super(CreateAuthor, self).get_context_data(**kwargs)
        context["action_url"] = 'libraryapp:create_author'
        return context

    def form_valid(self, form):
        instance = form.save()
        author_id = instance.id
        return HttpResponseRedirect(reverse('libraryapp:create_theme', kwargs={'author_id': author_id}))


class CreateTheme(CreateView):
    model = Themes
    template_name = 'libraryapp/create_theme.html'
    form_class = ThemeCreationForm
    author_id = 0

    def get(self, request, *args, **kwargs):
        self.author_id = self.kwargs['author_id']
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.author_id = self.kwargs['author_id']
        return super().post(request, *args, *kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action_url'] = 'libraryapp:create_theme'
        context['author_id'] = self.author_id
        return context

    def form_valid(self, form):
        instance = form.save()
        kwargs = {'author_id': self.author_id,
                  'theme_id': instance.id}
        return HttpResponseRedirect(reverse('libraryapp:create_ref', kwargs=kwargs))


class CreateRef(CreateView):
    model = References
    template_name = 'libraryapp/create_ref.html'
    form_class = ReferenceCreationForm

    def __init__(self, *args, **kwargs):
        super(CreateRef, self).__init__(*args, **kwargs)
        self.author_id = ''
        self.theme_id = ''

    def get(self, request, *args, **kwargs):
        self.author_id = self.kwargs['author_id']
        self.theme_id = self.kwargs['theme_id']
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.author_id = self.kwargs['author_id']
        self.theme_id = self.kwargs['theme_id']
        return super().post(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action_url'] = 'libraryapp:create_ref'
        context['author_id'] = self.author_id
        context['theme_id'] = self.theme_id
        return context

    def form_valid(self, form):
        instance = form.save()
        
        kwargs = {'author_id': self.author_id,
                  'theme_id': self.theme_id,
                  'ref_id': instance.id}
        return HttpResponseRedirect(reverse('libraryapp:create_article', kwargs=kwargs))


class EditArticle(UpdateView):
    model = Article
    template_name = 'libraryapp/edit_article.html'
    form_class = ArticleCreationForm

    def __init__(self, *args, **kwargs):
        super(EditArticle, self).__init__(*args, **kwargs)
        self.article_id = ''

    def get(self, request, **kwargs):
        self.article_id = self.kwargs['pk']
        return super().get(request, **kwargs)

    def get_queryset(self, **kwargs):
        return Article.objects.filter(pk=self.article_id)

    def post(self, request, **kwargs):
        self.article_id = self.kwargs['pk']
        return super().post(request, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pk'] = self.article_id
        return context

    def form_valid(self, form):
        instance = form.save()
        instance.save()
        return HttpResponseRedirect(reverse('library:article', kwargs={'pk': self.article_id}))


class EditTheme(UpdateView):
    model = Themes
    form_class = ThemeCreationForm
    template_name = 'libraryapp/edit_theme.html'

    def __init__(self, *args, **kwargs):
        super(EditTheme, self).__init__(*args, **kwargs)
        self.theme_id = ''
        self.article_id = ''

    def get(self, request, *args, **kwargs):
        self.theme_id = self.kwargs['pk']
        self.article_id = self.kwargs['article_id']
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.theme_id = self.kwargs['pk']
        self.article_id = self.kwargs['article_id']
        return super().post(request, *args, **kwargs)

    def get_queryset(self):
        return Themes.objects.filter(pk=self.theme_id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pk'] = self.theme_id
        context['article_id'] = self.article_id
        return context

    def form_valid(self, form):
        instance = form.save()
        instance.save()

article_base/libraryapp/templates/libraryapp/article.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% block content %}
    <div class="article_i">
        <div class="article_title">
            <a href="{% url 'library:article' article.id %}"> {{ article.title }}</a>
        </div>
        <div class="article_source">
            {{ article.source }}
        </div>
        <div class="article_year">
            {{ article.year }}
        </div>
        <div class="article_abstract">
            {{ article.abstract }}
            <div>
                <a class="edit" href="{% url 'library:edit_article' article.id %}">Редактировать</a>
            </div>
        </div>
        <div class="article_themes">
            <ul>
                {% for theme in article.theme.get_list %}
                <li>
                    {{ theme }}
                </li>
                {% endfor %}
            </ul>
            {{ article.themes }}
            <a class="edit" href="{% url 'library:edit_theme' article.id article.theme.id %}">Редактировать</a>
        </div>
        <div class="article_authors">
            <ul>
                {% for author in article.author.get_list %}
                    <li>{{ author }}</li>
                {% endfor %}
            </ul>
            <a class="edit" href="{% url 'library:edit_author' article.id article.author.id %}">Редактировать</a>
        </div>
        <div class="article_refs">
            <ol>
            {% for reference in article.reference.get_list %}
                <li>
                    {{ reference }}
                </li>
            {% endfor %}
            </ol>
            <a class="edit" href="{% url 'library:edit_refs' article.id article.reference.id %}">Редактировать</a>
        </div>
    </div>
    <div class="article_actions">
        <ul>
            <li><a href="{% url 'library:open_pdf' pk=article.id %}">Открыть PDF</a></li>
            <li>
                {% if article_added %}
                    <a href="{% url 'library:delete_from_shelf' article.id %}" >Удалить c Моей Полки</a>
                {% else %}
                    <a href="{% url 'library:add_shelf' article.id %}" >Добавить на Мою Полку</a>
                {% endif %}
            </li>
        </ul>
    </div>
{% endblock %}

article_base/libraryapp/templates/libraryapp/create_article.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% block content %}
    <div style="width: 400px; margin: 0 auto;">
        <form action="{% url action_url author_id theme_id ref_id %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Добавить" class="form-control">
        </form>
    </div>
{% endblock %}

article_base/libraryapp/templates/libraryapp/create_author.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% block content %}
    <div style="width: 400px; margin: 0 auto;">
        <form action="{% url action_url %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Добавить" class="form-control">
        </form>
    </div>
{% endblock %}

article_base/libraryapp/templates/libraryapp/create_ref.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% block content %}
    <div style="width: 400px; margin: 0 auto;">
        <form action="{% url action_url author_id theme_id %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Добавить" class="form-control">
        </form>
    </div>
{% endblock %}

article_base/libraryapp/templates/libraryapp/create_theme.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% block content %}
    <div style="width: 400px; margin: 0 auto;">
        <form action="{% url action_url author_id %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Добавить" class="form-control">
        </form>
    </div>
{% endblock %}

article_base/libraryapp/templates/libraryapp/edit_article.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% block content %}
    <div style="width: 400px; margin: 0 auto;">
        <form action="{% url 'libraryapp:edit_article' pk %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Добавить" class="form-control">
        </form>
    </div>
{% endblock %}

article_base/libraryapp/templates/libraryapp/edit_author.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% block content %}
    <div style="width: 400px; margin: 0 auto;">
        <form action="{% url 'libraryapp:edit_author' article_id pk %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Добавить" class="form-control">
        </form>
    </div>
{% endblock %}

article_base/libraryapp/templates/libraryapp/edit_refs.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% block content %}
    <div style="width: 400px; margin: 0 auto;">
        <form action="{% url 'libraryapp:edit_refs' article_id pk %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Добавить" class="form-control">
        </form>
    </div>
{% endblock %}

article_base/libraryapp/templates/libraryapp/edit_theme.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% block content %}
    <div style="width: 400px; margin: 0 auto;">
        <form action="{% url 'libraryapp:edit_theme' article_id pk %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Добавить" class="form-control">
        </form>
    </div>
{% endblock %}

article_base/libraryapp/templates/libraryapp/library.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
	{% block content %}
		<div class="filters">
			<form action="{% url 'library:index' %}" method="post">
				{% csrf_token %}
				<h3>Фильтры</h3>
				<fieldset>
					<legend>Название статьи</legend>
					<input type="textbox" name="title" >
				</fieldset>
				<fieldset>
					<legend>Автор</legend>
					<input type="textbox" name="author" >
				</fieldset>
				<fieldset>
					<legend>DOI</legend>
					<input type="textbox" name="doi">
				</fieldset>
				<fieldset>
					<legend>Год</legend>
					<input class="input_year" type="textbox" name="year__gte">
					<input class="input_year" type="textbox" name="year__lte">
				</fieldset>
				<fieldset class="themes" name="request_themes">
					<legend>Тематики</legend>
						<ul>
							{% for key, value in themes.items %}
							<li>
								<input type="checkbox" id="{{ key }}" name="{{ key }}">
								<label for="{{ key }}">{{ value }}</label>
							</li>
							{% endfor %}
						</ul>
				</fieldset>
				<fieldset class="sources" name="request_sources">
					<legend>Источник</legend>
					<ul>
						{% for object in sources %}
						<li>
							<input type="checkbox" id="{{ object }}" name="{{ object }}">
							<label for="{{ object }}">{{ object.source }}</label>
						</li>
						{% endfor %}
					</ul>

				</fieldset>
				<fieldset>
					<legend>Публикация ЦК</legend>
					<input type="checkbox" name="ours">
				</fieldset>
				<fieldset>
					<input type="submit" value="Поиск">
				</fieldset>

			</form>
			
		</div>
		<div class="article_prev">
			<a href="{% url 'libraryapp:create_author' %}">Добавить статью</a>
			<ul>
				{% for article in articles %}
				<li>
					<div class="article_i">
						<div class="article_title">
							<a href="{% url 'library:article' article.id %}"> {{ article.title }}</a>
						</div>
						<div class="article_abstract">
							{{ article.abstract }}
						</div>

						<div class="article_authors">
							<ul>
								{% for author in article.author.get_list %}
									<li>{{ author }}</li>
								{% endfor %}
							</ul>
						</div>
						<div class="article_year">{{ article.year }}
						</div>
					</div>
				</li>
				{% endfor %}
			</ul>
		</div>
		<div class="paginator">
			{% if articles.has_previous %}
				<a href="{% url 'library:page' articles.previous_page_number %}">
					<
				</a>
			{% endif %}
			<span class="current">
				страница {{ articles.number }} из {{ articles.paginator.num_pages }}
			</span>
			{% if articles.has_next %}
				<a href="{% url 'library:page' articles.next_page_number %}">
					>
				</a>
			{% endif %}
		</div>
		<div class="clear_both"></div>
	{% endblock %}

article_base/libraryapp/templates/libraryapp/list_view.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% block content %}
    {% for object in object_list %}
        <p>{{ object.author }}</p>
    {% endfor %}
    {{ stuff }}
{% endblock %}