article_base/article_base/urls.py
from django.contrib import admin
from django.urls import path
from mainapp import views as mainapp
from libraryapp import views as libraryapp
from shelfapp import views as shelfapp
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include


urlpatterns = [
    path('', mainapp.index, name='main'),
    path('library/', include('libraryapp.urls', namespace='library')),
    path('bookshelf/', include('shelfapp.urls', namespace='bookshelf')),
    path('profile', libraryapp.library, name='profile'),
    path('admin/', admin.site.urls, name='admin'),
    path('auth/', include('authapp.urls', namespace='auth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

article_base/authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
]

article_base/mainapp/views.py
from django.shortcuts import render
import json

# added open from json file links in menu

with open('static/json/links.json', 'r', encoding="UTF-8") as read_file:
    links = json.load(read_file)['links']
# Create your views here.


def index(request):
    title = 'Главная'
    content = {'title': title,
               'links': links,
               }
    return render(request, "mainapp/index.html", content)


def library(request):
    pass


def bookshelf(request):
    pass


def profile(request):
    pass

article_base/mainapp/templates/mainapp/includes/inc_menu.html
<ul class="menu_main">
    {% for link in links %}
        {% if link.name == "library:page" %}
            <li>
                <a href="{% url link.name '1' %}">
                    {{ link.title }}
                </a>
            </li>
        {% elif link.name == "bookshelf:page" %}
                <li>
                    <a href="{% url link.name '1' %}">
                        {{ link.title }}
                    </a>
                </li>
        {% else %}
            <li><a href="{% url link.name %}"
            class="{% if link.name == request.resolver_match.url_name %}
                   active
                   {% endif %}"
            >{{ link.title }}</a></li>
        {% endif %}
    {% endfor %}
    <li><a href="{% url 'auth:logout' %}">Выйти</a></li>
    {% if user.is_superuser %}
    <li><a href="{% url 'admin:index' %}">Управление</a></li>
    {% endif %}
</ul>