article_base/article_base/urls.py
from django.contrib import admin
from django.urls import path
from mainapp import views as mainapp
from libraryapp import views as libraryapp
from shelfapp import views as shelfapp
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include


urlpatterns = [
    path('', mainapp.index, name='main'),
    path('library/', include('libraryapp.urls', namespace='library')),
    path('bookshelf/', include('shelfapp.urls', namespace='bookshelf')),
    path('profile', libraryapp.library, name='profile'),
    path('admin/', admin.site.urls, name='admin'),
    path('auth/', include('authapp.urls', namespace='auth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

article_base/authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
]

article_base/libraryapp/urls.py
from django.urls import path

import libraryapp.views as libraryapp

app_name = 'libraryapp'

urlpatterns = [
    path('', libraryapp.library, name='index'),
    path('page/<int:page>/', libraryapp.library, name='page'),
    path('listview/', libraryapp.ArticleView.as_view(), name='listview'),
    path('create_author/', libraryapp.CreateAuthor.as_view(), name='create_author'),
    path('create_theme/<int:author_id>/', libraryapp.CreateTheme.as_view(), name='create_theme'),
    path('create_ref/<int:author_id>/<int:theme_id>/', libraryapp.CreateRef.as_view(), name='create_ref'),
    path('create_article/<int:author_id>/<int:theme_id>/<int:ref_id>', libraryapp.CreateArticle.as_view(), name='create_article'),
    path('edit_article/<int:pk>/', libraryapp.EditArticle.as_view(), name='edit_article'),
    path('edit_theme/<int:article_id>/<int:pk>/', libraryapp.EditTheme.as_view(), name='edit_theme'),
    path('edit_author/<int:article_id>/<int:pk>/', libraryapp.EditAuthor.as_view(), name='edit_author'),
    path('edit_refs/<int:article_id>/<int:pk>/', libraryapp.EditRefs.as_view(), name='edit_refs'),
    path('article/<int:pk>/', libraryapp.article, name='article'),
    path('add_shelf/<int:pk>/', libraryapp.add_shelf, name='add_shelf'),
    path('delete_from_shelf/<int:pk>', libraryapp.delete_from_shelf, name='delete_from_shelf'),
    path('open_pdf/<int:pk>/', libraryapp.open_pdf, name='open_pdf'),
]

article_base/shelfapp/urls.py
from django.urls import path

import shelfapp.views as shelfapp

app_name = 'shelfapp'

urlpatterns = [
    path('', shelfapp.bookshelf, name='index'),
    path('page/<int:page>/', shelfapp.bookshelf, name='page'),
    path('article/<int:pk>/', shelfapp.article, name='article'),
]

article_base/shelfapp/models.py
from django.db import models
from libraryapp.models import Article
from authapp.models import Scientist

# Create your models here.


class Bookshelf(models.Model):
    user = models.ForeignKey(Scientist, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    add_datetime = models.DateTimeField(verbose_name="время", auto_now_add=True)

    class Meta:
        verbose_name = "Полка"
        verbose_name_plural = "Полки"
        unique_together = (('user', 'article'),)

article_base/shelfapp/views.py
from django.shortcuts import render
from libraryapp import views
from .models import Bookshelf
from libraryapp.models import Sources, Article, Themes
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator

# Create your views here.


def bookshelf(request, page=1):
    title = 'Книжная полка'
    links = views.load_links()
    themes = views.load_themes()
    sources = Sources.objects.all()
    articles_id = []
    user_articles = Bookshelf.objects.filter(user=request.user)
    for user_article in user_articles:
        articles_id.append(user_article.article.id)
    articles = Article.objects.filter(id__in=articles_id)
    if request.method == "POST":
        articles = views.filter_articles(articles, request)
    paginator = Paginator(articles, 4)
    try:
        pag_articles = paginator.page(page)
    except PageNotAnInteger:
        pag_articles = paginator.page(1)
    except EmptyPage:
        pag_articles = paginator.page(paginator.num_pages)
    content = {'title': title,
               'themes': themes,
               'sources': sources,
               'links': links,
               'articles': pag_articles,
               }

    return render(request, "libraryapp/library.html", content)


def article(request, pk=None):
    article_pk = get_object_or_404(Article, pk=pk)
    links = views.load_links()
    content = {'links': links,
               'article': article_pk,
               }

    return render(request, "shelfapp/article.html", content)

article_base/shelfapp/templates/shelfapp/article.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% block content %}
    <div class="article_i">
        <div class="article_title">
            <a href="{% url 'bookshelf:article' article.id %}"> {{ article.title }}</a>
        </div>
        <div class="article_source">
            {{ article.source }}
        </div>
        <div class="article_year">
            {{ article.year }}
        </div>
        <div class="article_abstract">
            {{ article.abstract }}
        </div>
        <div class="article_themes">
            <ul>
                {% for theme in article.theme.get_list %}
                <li>
                    {{ theme }}
                </li>
                {% endfor %}
            </ul>
            {{ article.themes }}
        </div>
        <div class="article_authors">
            <ul>
                {% for author in article.author.get_list %}
                    <li>{{ author }}</li>
                {% endfor %}
            </ul>
        </div>
        <div class="article_refs">
            <ol>
            {% for reference in article.reference.get_list %}
                <li>
                    {{ reference }}
                </li>
            {% endfor %}
            </ol>

        </div>
    </div>
    <div class="article_actions">
        <ul>
            <li><a href="{% url 'library:open_pdf' pk=article.id %}">Открыть PDF</a></li>
            <li><a href="{% url 'library:add_shelf' pk=article.id %}" target="_blank">Добавить на Мою Полку</a></li>
            <li><a href="">Редактировать</a></li>
        </ul>
    </div>
{% endblock %}

article_base/shelfapp/templates/shelfapp/library.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
	{% block content %}
		<div class="filters">
			<form action="{% url 'library:index' %}" method="post">
				{% csrf_token %}
				<h3>Фильтры</h3>
				<fieldset>
					<legend>Название статьи</legend>
					<input type="textbox" name="title" >
				</fieldset>
				<fieldset>
					<legend>Автор</legend>
					<input type="textbox" name="author" >
				</fieldset>
				<fieldset>
					<legend>DOI</legend>
					<input type="textbox" name="doi">
				</fieldset>
				<fieldset>
					<legend>Год</legend>
					<input class="input_year" type="textbox" name="year__gte">
					<input class="input_year" type="textbox" name="year__lte">
				</fieldset>
				<fieldset class="themes" name="request_themes">
					<legend>Тематики</legend>
						<ul>
							{% for key, value in themes.items %}
							<li>
								<input type="checkbox" id="{{ key }}" name="{{ key }}">
								<label for="{{ key }}">{{ value }}</label>
							</li>
							{% endfor %}
						</ul>
				</fieldset>
				<fieldset class="sources" name="request_sources">
					<legend>Источник</legend>
					<ul>
						{% for object in sources %}
						<li>
							<input type="checkbox" id="{{ object }}" name="{{ object }}">
							<label for="{{ object }}">{{ object.source }}</label>
						</li>
						{% endfor %}
					</ul>

				</fieldset>
				<fieldset>
					<legend>Публикация ЦК</legend>
					<input type="checkbox" name="ours">
				</fieldset>
				<fieldset>
					<input type="submit" value="Поиск">
				</fieldset>

			</form>
			
		</div>
		<div class="article_prev">
			<ul>
				{% for article in articles %}
				<li>
					<div class="article_i">
						<div class="article_title">
							<a href="{% url 'bookshelf:article' article.id %}"> {{ article.title }}</a>
						</div>
						<div class="article_abstract">
							{{ article.abstract }}
						</div>

						<div class="article_authors">
							<ul>
								{% for author in article.author.get_list %}
									<li>{{ author }}</li>
								{% endfor %}
							</ul>
						</div>
						<div class="article_year">{{ article.year }}
						</div>
					</div>
				</li>
				{% endfor %}
			</ul>
		</div>
		<div class="clear_both"></div>
	{% endblock %}